ARG CUDA_VERSION="11.8.0"
ARG CUDNN_VERSION="8"
ARG UBUNTU_VERSION="20.04"
ARG MAX_JOBS=4

FROM nvidia/cuda:$CUDA_VERSION-cudnn$CUDNN_VERSION-runtime-ubuntu$UBUNTU_VERSION

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    software-properties-common && \
    add-apt-repository -y ppa:deadsnakes/ppa

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    python3.12 \
    wget \
    curl \
    unzip \
    git \
    libgl1 \
    libglib2.0-0 \
    curl \
    gnupg2 \
    ca-certificates \
    apt-transport-https \
    libreoffice \
    ffmpeg \
    git-lfs \
    xvfb

RUN apt-get install -y --no-install-recommends python3.12-venv
# && rm -rf /var/lib/apt/lists/*


ARG UID=11132
ARG GID=11133

ENV HOME=/home/llm-apps
RUN addgroup --gid $GID llm-adm && adduser --uid $UID --ingroup llm-adm --disabled-password -q --gecos llm llm-apps

ARG APP_DIR=/app
WORKDIR $APP_DIR
COPY ./ ./
RUN mkdir /data
RUN chown -R $UID:$GID $APP_DIR /data
USER $UID:$GID
RUN python3.12 -m venv $APP_DIR/.venv && . $APP_DIR/.venv/bin/activate && \
  pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 && \
  pip install --no-cache-dir .

# Copy the project files into the Docker image

#RUN python -c 'from marker.models import load_all_models; load_all_models()'

EXPOSE 8080

CMD ["/app/run.sh"]
